/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parse_only;

import java.util.List;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

public class App {
    public static void main(String[] args) {
        Options options = new Options();
        new CommandLine(options).parseArgs(args);
        System.out.println(options);
    }
}

class Options {
    @Option(names = { "-s", "--string" }, paramLabel = "VALUE", description = "文字列渡せますよー")
    private String optionString;

    @Option(names = { "-i", "--integer" }, paramLabel = "VALUE", description = "整数(integer)渡せますよー")
    private int optionInteger;

    @Option(names = { "-l", "--long" }, paramLabel = "VALUE", description = "整数(long)渡せますよー")
    private long optionLong;

    @Option(names = { "-f", "--float" }, paramLabel = "VALUE", description = "小数(float)渡せますよー")
    private float optionFloat;

    @Option(names = { "-d", "--double" }, paramLabel = "VALUE", description = "小数(double)渡せますよー")
    private double optionDouble;

    @Option(names = { "-b", "--boolean" }, paramLabel = "VALUE", description = "真偽(boolean)渡せますよー")
    private boolean optionBoolean;

    @Parameters(description = "コマンドラインパラメーター")
    private List<String> params;

    @Override
    public String toString() {
        return String.format("optionString: %s\n", optionString)
            + String.format("optionInteger: %s\n", optionInteger)
            + String.format("optionLong: %s\n", optionLong)
            + String.format("optionFloat: %s\n", optionFloat)
            + String.format("optionDouble: %s\n", optionDouble)
            + String.format("optionBooldan: %s\n", optionBoolean)
            + String.format("params: %s\n", params);
    }
}
