/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.dip.oyasirazu.study.yaml.jackson.anchorandalias;

import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Map;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

public class App {
    public static void main(String[] args) throws IOException {
        var mapper = new ObjectMapper(new YAMLFactory());
        var config = mapper.readValue(new InputStreamReader(
                    ClassLoader.getSystemResourceAsStream("Config.yaml"),
                    "UTF-8"), Map.class);

        System.out.println(config);
    }
}
