version: '3'

services:
  app:
    environment:
      SHELL: bash
    volumes:
      # vim 設定ファイル
      - "~/.vim:/root/.vim"
      # vim 配置場所
      - "vim:/vim"
  vim-installer:
    image: alpine/curl
    init: true
    restart: "no"
    depends_on:
      - app
    volumes:
      # インストールスクリプト
      - "./.devcontainer/script/vim-installer/vim-install.sh:/vim-install.sh"
      # vim 配置場所
      - "vim:/vim"
    command:
      - sh
      - /vim-install.sh

volumes:
  vim:

