spring:
  application:
    name: springaifirststep
  ai:
    ollama:
      base-url: http://host.docker.internal:11434
      chat:
        options:
          model: qwen3.5:9b
          temperature: 0.7
