spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
        jdbc:
          core: TRACE


