snippets:
    javascript:
        - label: func
          description: function
          newText: |-
              function ${1:name}(${2:args}) {
                  ${3:content}
              }
        - label: if
          description: if statement
          newText: |-
              if (${1:condition}) {
                  ${2:expr}
              }
        - label: for
          description: for statement
          newText: |-
              for (${1:initial} : ${2:condition} : ${3:increment}) {
                  ${4:expr}
              }
    java:
        - label: getter
          description: getter method
          newText: |-
              public ${1:type} get${2:func_name}() {
                  return ${2:field_name}
              }
        - label: setter
          description: setter method
          newText: |-
              public void set${1:func_name}(${2:type} {3:field_name}) {
                  this.${4:field_name} = {5:field_name}
              }

