version: '3'

services:
  app:
    image: eclipse-temurin:21
    init: true
    restart: always
    command: ["sleep", "infinity"]
    volumes:
      # プロジェクトルート
      - "./:/work"
    working_dir: /work
