[package]
name = "firststep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.19.4", features = ["with-uuid-1"] }
uuid = "1.2.2"

