import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { FirststepGeneratedModule, FirststepGeneratedSharedModule } from './generated/module';
import { FirststepValidationRegistry, FirststepValidator } from './firststep-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type FirststepAddedServices = {
    validation: {
        FirststepValidator: FirststepValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type FirststepServices = LangiumServices & FirststepAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const FirststepModule: Module<FirststepServices, PartialLangiumServices & FirststepAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new FirststepValidationRegistry(services),
        FirststepValidator: () => new FirststepValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createFirststepServices(context?: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Firststep: FirststepServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        FirststepGeneratedSharedModule
    );
    const Firststep = inject(
        createDefaultModule({ shared }),
        FirststepGeneratedModule,
        FirststepModule
    );
    shared.ServiceRegistry.register(Firststep);
    return { shared, Firststep };
}
