services:
  dev:
    image: tomcat:9.0
    container_name: dev
    env:
      CATALINA_OPTS: "-Dspring.profiles.active=dev"
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT

  prod:
    image: tomcat:9.0
    container_name: prod
    env:
      CATALINA_OPTS: "-Dspring.profiles.active=prod"
    ports:
      - "8081:8080"
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT

  dev-java:
    image: mcr.microsoft.com/vscode/devcontainers/java:0-bookworm
    container_name: dev-java
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    stdin_open: true
    tty: true
