services:
  app:
    image: "mcr.microsoft.com/devcontainers/java:3-25-trixie"
    ports:
      - "8080"
    command: ['sh', '-c',  'trap "exit 0" TERM; sleep infinity & wait']
    volumes:
      - .:/workspaces
      - m2-cache:/home/vscode/.m2
    working_dir: "/workspaces"
  prometheus:
    image: prom/prometheus
    ports:
      - '9090'
    volumes:
     - './prometheus.yaml:/etc/prometheus/prometheus.yml'
     - './rules.yaml:/etc/prometheus/rules.yml'
     - 'prometheus-data:/prometheus'
  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./dashboard_provider.yaml:/etc/grafana/provisioning/dashbords/dashbords.yml:ro
      - ./prometheus_dashboard.json:/etc/grafana/dashboards/prometheus_dashboard.json:ro
    depends_on:
      - prometheus
volumes:
  prometheus-data: {}
  grafana-data: {}
  m2-cache:
    external: true
