version: '3'
services:
    java:
      image: mcr.microsoft.com/devcontainers/java:21-bookworm
      volumes:
        - "./:/workspaces"
        - "m2-volume:/home/vscode/.m2"
      working_dir: "/workspaces"
      command: ["sleep", "infinity"]
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: public
    postgres:
      image: postgres:17
      volumes:
        # 初期化スクリプト置き場
        - ./config/postgres/init.d:/docker-entrypoint-initdb.d
      ports:
        - "0.0.0.0:5432:5432"
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: public
volumes:
  m2-volume:
    name: m2-cache


