version: '3'

services:
  app:
    image: rust
    init: true
    environment:
      POSTGRES_HOST: "postgres:5432"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    command:
      - sleep
      - infinity
    volumes:
      - "./project:/project"
    working_dir: /project
  postgres:
    image: postgres:15
    init: true
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./conf/postgres/init.d/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "0.0.0.0:5432:5432"

volumes:
  postgres_data:
    driver: local

