/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subcommand;

import java.util.List;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command( name = "App", mixinStandardHelpOptions = true, version = "App 1.0.0", subcommands = { DecimalCommand.class, WholeNumberCommand.class } )
public class App implements Callable<Integer> {
    public static void main(String[] args) {
        int returnCode = new CommandLine(new App()).execute(args);
        System.exit(returnCode);
    }

    @Override
    public Integer call() {
        return 0;
    }
}

@Command( name = "DecimalCommand", aliases = { "decimal" }, description = "小数を渡せるサブコマンド" )
class DecimalCommand implements Callable<Integer> {
    @Option(names = { "-f", "--float" }, paramLabel = "VALUE", description = "小数(float)渡せますよー")
    private float optionFloat;

    @Option(names = { "-d", "--double" }, paramLabel = "VALUE", description = "小数(double)渡せますよー")
    private double optionDouble;

    @Override
    public Integer call() {
        System.out.println(String.format("optionFloat: %s", optionFloat));
        System.out.println(String.format("optionDouble: %s", optionDouble));
        return 0;
    }
}

@Command( name = "WholeNumberCommand", aliases = { "whole" }, description = "整数を渡せるサブコマンド" )
class WholeNumberCommand implements Callable<Integer> {
    @Option(names = { "-i", "--integer" }, paramLabel = "VALUE", description = "整数(integer)渡せますよー")
    private int optionInteger;

    @Option(names = { "-l", "--long" }, paramLabel = "VALUE", description = "整数(long)渡せますよー")
    private long optionLong;

    @Override
    public Integer call() {
        System.out.println(String.format("optionInteger: %s", optionInteger));
        System.out.println(String.format("optionLong: %s", optionLong));
        return 0;
    }
}

