/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.dip.oyasirazu.study.yaml.snakeyaml.anchorandalias;

import java.io.IOException;
import java.io.InputStreamReader;

import org.yaml.snakeyaml.Yaml;

public class App {
    public static void main(String[] args) throws IOException {
        var yaml = new Yaml();

        var config = yaml.load(
                new InputStreamReader(
                    ClassLoader.getSystemResourceAsStream("Config.yaml"),
                    "UTF-8"));

        System.out.println(config);
    }
}
