package dev.mikoto2000.study.springboot.data.jpa.firststep.entity;
// Generated Oct 22, 2023, 6:23:58 PM by Hibernate Tools 6.3.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="Account"
    ,catalog="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Account  implements java.io.Serializable {


     private long id;
     private Role role;
     private String name;
     private Set<Attendance> attendances = new HashSet<Attendance>(0);

    public Account() {
    }

    public Account(long id, Role role, String name, Set<Attendance> attendances) {
       this.id = id;
       this.role = role;
       this.name = name;
       this.attendances = attendances;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="name", unique=true, nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<Attendance> getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set<Attendance> attendances) {
        this.attendances = attendances;
    }




}


