package dev.mikoto2000.study.springboot.data.jpa.firststep.entity;
// Generated Oct 22, 2023, 11:29:42 AM by Hibernate Tools 6.3.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="Role"
    ,catalog="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Role  implements java.io.Serializable {


     private long id;
     private String name;

    public Role() {
    }

    public Role(long id, String name) {
       this.id = id;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


