package dev.mikoto2000.study.springboot.data.jpa.firststep.entity;
// Generated Oct 22, 2023, 11:57:50 AM by Hibernate Tools 6.3.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
@AllArgsConstructor
@Entity
@Table(name="Role"
    ,catalog="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
@ToString(exclude = "accounts")
@EqualsAndHashCode()
public class Role  implements java.io.Serializable {


     private Long id;
     private String name;
     @EqualsAndHashCode.Exclude
     private Set<Account> accounts = new HashSet<Account>(0);

    public Role() {
    }

    public Role(String name, Set<Account> accounts) {
       this.name = name;
       this.accounts = accounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


