spring:
  application:
    name: firststep

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
