spring:
  application:
    name: springaifirststep
  datasource:
    url: jdbc:sqlite:./target/test.db
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    ollama:
      base-url: http://host.docker.internal:11434
      chat:
        options:
          model: qwen3.5:9b
          temperature: 0.7

